	INSERT INTO `rubro` (`id`, `nombre`, `icono`) VALUES
	(NULL, 'Otros', 'plus'),
	(NULL, 'Alojamientos', 'bed'),
	(NULL, 'Hoteles', 'h-square '),
	(NULL, 'Peluquerias', 'cut'),
	(NULL, 'Talleres', 'wrench'),
	(NULL, 'RadioMoviles', 'taxi'),
	(NULL, 'Universidades', 'university'),
	(NULL, 'Farmacias', 'pills'),
	(NULL, 'Hospitales', 'ambulance'),
	(NULL, 'Veterinarias', 'paw'),
	(NULL, 'Colegios', 'graduation-cap'),
	(NULL, 'Bancos', 'dollar-sign	'),
	(NULL, 'Supermercados', 'shopping-cart '),
	(NULL, 'Florerias', 'leaf'),
	(NULL, 'Laboratorios', 'flask'),
	(NULL, 'Cooperativas', 'money-bill-alt'),
	(NULL, 'Cafeterias', 'coffee'),
	(NULL, 'Pasteleria', 'birthday-cake'),
	(NULL, 'Librerias', 'book'),
	(NULL, 'Institutos', 'pencil-alt '),
	(NULL, 'Tintorerias', 'black-tie'),
	(NULL, 'Restaurantes', 'utensils'),
	(NULL, 'Industrias', 'industry'),
	(NULL, 'Cines', 'film');


